#!python

# vrkit is (C) Copyright 2005-2007
#    by Allen Bierbaum, Aron Bierbuam, Patrick Hartling, and Daniel Shipton
#
# This file is part of vrkit.
#
# vrkit is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# vrkit is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import glob, os
import os.path
import SConsAddons.Util as sca_util

pj = os.path.join

Import('*')

env = baseEnv.Copy()
env.Append(CPPPATH = [inst_paths['include']] )    # Need to find the IOV directory

header_path = pj(inst_paths['include'],'IOV')

src_files = []
header_files = []
def_files = []
for path, dirs, files in sca_util.WalkBuildFromSource('.',env):
   src_files += [pj(path,f) for f in files if f.endswith('.cpp')]
   header_files += [pj(path,f) for f in files if f.endswith('.h')]
   def_files += [pj(path,f) for f in files if f.endswith('.jdef')]

iov_lib = env.SharedLibrary('iov', src_files)

# Install the library, headers, and definitions
env.Install(inst_paths['lib'], iov_lib)
env.InstallAs(target = [pj(header_path, h) for h in header_files],
                 source = header_files)
env.Install(inst_paths['definitions'], def_files)
