#!python

import glob, os
import os.path
import SConsAddons.Util as sca_util

pj = os.path.join

Import('baseEnv optimize')
Import('GetPlatform')

env = baseEnv.Copy()
env.Append(CPPPATH = [os.path.join('..', '..', '..', '..')])

src_files = []
for path, dirs, files in sca_util.WalkBuildFromSource('.',env):
   src_files += [pj(path,f) for f in files if f.endswith('.cpp')]

env.SharedLibrary('iov', src_files)
