#!python

import glob, os
import os.path
pj = os.path.join

Import('baseEnv optimize')
Import('GetPlatform')

env = baseEnv.Copy()
env.Append(CPPPATH = [os.path.join('..', '..', '..', '..')])

src_files = []
for path, dirs, files in os.walk('.'):
   src_files += [pj(path,f) for f in files if f.endswith('.cpp')]

env.SharedLibrary('iov', src_files)
