#!python
#
import SConsAddons.Util       # Get the utils
import sys, os, re, string, glob
pj = os.path.join
GetPlatform = SConsAddons.Util.GetPlatform;

Import('*')

viewerEnv = base_env.Copy()

boost_options.apply(viewerEnv)

if boost_options.isAvailable():
   viewerEnv.Prepend(CPPPATH = inst_paths['include'],
                     LIBPATH = inst_paths['lib'],
                     LIBS = 'iov'+shared_lib_suffix)
   viewerEnv.Append(CPPPATH = ['.'])

   # XXX: There has to be a better way to do this Mac-specific stuff.
   if GetPlatform() == 'darwin':
      viewerEnv.Append(LINKFLAGS = ['-Wl,-bind_at_load'])

   po_lib = boost_options.getFullLibName('program_options', viewerEnv)
   viewerEnv.Prepend(LIBS = [po_lib])

   slave_viewer_name = 'slaveViewer' + runtime_suffix
   slave_viewer_prog = viewerEnv.Program(slave_viewer_name, ['slave_app.cpp'])
   viewerEnv.Install(pj(inst_paths['app_base'],'slaveViewer'), slave_viewer_prog)
else:
   print "WARNING: Cannot build slaveViewer without Boost.program_options"

