#!python
#
import SConsAddons.Util       # Get the utils
import sys, os, re, string, glob
pj = os.path.join
GetPlatform = SConsAddons.Util.GetPlatform;

Import('*')

ui_env = baseEnv.Copy()
opensg_options.updateEnv(ui_env, lib='glut')
ui_env.Prepend(CPPPATH = inst_paths['include'],
               LIBPATH = inst_paths['lib'],
               LIBS = 'iov')

uitest_prog = ui_env.Program('ui_test', ['ui_test.cpp',])
ui_env.Install(pj(inst_paths['test_base'],'UITest'), uitest_prog)

