#!python
#
import SConsAddons.Util       # Get the utils
import sys, os, re, string, glob
pj = os.path.join
GetPlatform = SConsAddons.Util.GetPlatform;

Import('*')

if GetPlatform() == 'darwin':
   mac_cflags = os.popen(opensg_options.osgconfig_cmd + " --cflags GLUT").read()
   opensg_options.found_cflags = mac_cflags.strip().split(" ")

ui_env = build_env.Copy()
opensg_options.apply(ui_env, libs = ['glut'])

ui_env.Prepend(CPPPATH = inst_paths['include'],
               LIBPATH = inst_paths['lib'])

if platform == 'darwin':
   ui_env.Append(LINKFLAGS = ['-framework', 'Cocoa',
                              '-framework', 'GLUT',
                              '-framework', 'OpenGL'])

if platform != 'win32':
   ui_env.Prepend(LIBS = ['iov' + shared_lib_suffix])

plugin_dir = os.path.join('..', '..', 'plugins', 'StatusPanelPlugin')
srcs = ['ui_test.cpp', os.path.join(plugin_dir, 'StatusPanel.cpp'),
        os.path.join(plugin_dir, 'StatusPanelViewOriginal.cpp')]
uitest_prog_name = 'ui_test' + runtime_suffix
uitest_prog = ui_env.Program(uitest_prog_name, srcs)
ui_env.Install(pj(inst_paths['test_base'],'UITest'), uitest_prog)
