#!python

import os.path
import SConsAddons.Util as sca_util

Import('*')

src_dir = sca_util.getFullSrcPath(env=SCons.Environment.Environment()):
plugin_dirs = [d for d in os.listdir(src_dir) if (os.path.isdir(pj(src_dir,f)) and not d.startswith('.'))]


#env.Append(CPPPATH = [os.path.join('..', '..', '..', '..')])
#env.Append(LIBPATH = [os.path.join('..', 'IOV')])
#env.Prepend(LIBS = ['iov'])

for plugin_name in plugin_dirs:
   plugin_srcs = []
   def_files = []
   for p, d, files in sca_util.WalkBuildFromSource('plugin_name',env):
      plugin_srcs += [pj(path,f) for f in files if f.endswith('.cpp')]
      def_files += [pj(path,f) for f in files if f.endswith('.jdef')]
   print "Plugin: ", plugin_name
   print "   srcs:", plugin_srcs
   print "   defs:", def_files
   lib_name = plugin_name
   if (optimize != 'yes'):
      lib_name += '_d'

for p in plugins:
   env.SharedLibrary(p.getName(), p.getSources(), SHLIBPREFIX = '')
