#!python

# vrkit is (C) Copyright 2005-2007
#    by Allen Bierbaum, Aron Bierbuam, Patrick Hartling, and Daniel Shipton
#
# This file is part of vrkit.
#
# vrkit is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# vrkit is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import SConsAddons.Util       # Get the utils
import sys, os, re, string, glob
pj = os.path.join
GetPlatform = SConsAddons.Util.GetPlatform;

Import('*')

viewerEnv = baseEnv.Copy()

boost_options.updateEnv(viewerEnv)

if boost_options.isAvailable():
   viewerEnv.Prepend(CPPPATH = inst_paths['include'],
                     LIBPATH = inst_paths['lib'],
                     LIBS = 'iov')

   # XXX: There has to be a better way to do this Mac-specific stuff.
   if GetPlatform() == 'mac':
      viewerEnv.Append(LINKFLAGS = ['-Wl,-bind_at_load'])

   viewerEnv.Prepend(LIBS = ['boost_program_options', 'OSGCluster', 'OSGState', 'OSGGroup', 'OSGDrawable', 'OSGWindow', 'OSGText', 'OSGRenderTraversal'])
   #po_lib = boost_options.buildFullLibName('program_options')
   #viewerEnv.Prepend(LIBS = [po_lib])

   jconf_files = ['viewer-nav.jconf', 'viewer-vp.jconf']
   infi_app_prog = viewerEnv.Program('infi_app', ['infi_app.cpp',])
   viewerEnv.Install(pj(inst_paths['app_base'],'Viewer'), infi_app_prog)
   viewerEnv.Install(pj(inst_paths['app_base'],'Viewer'), jconf_files)
else:
   print "WARNING: Cannot build infi_app without Boost.program_options"

