#!python
#
import SConsAddons.Util       # Get the utils
import sys, os, re, string, glob
pj = os.path.join
GetPlatform = SConsAddons.Util.GetPlatform;

Import('*')

viewerEnv = base_env.Copy()

boost_options.apply(viewerEnv)

if boost_options.isAvailable():
   viewerEnv.Prepend(CPPPATH = inst_paths['include'],
                     LIBPATH = inst_paths['lib'],
                     LIBS = 'iov'+shared_lib_suffix)

   # XXX: There has to be a better way to do this Mac-specific stuff.
   if GetPlatform() == 'darwin':
      viewerEnv.Append(LINKFLAGS = ['-Wl,-bind_at_load'])

   po_lib = boost_options.getFullLibName('program_options', viewerEnv)
   viewerEnv.Prepend(LIBS = [po_lib])

   infi_app_name = 'infi_app' + runtime_suffix
   infi_app_prog = viewerEnv.Program(infi_app_name, ['infi_app.cpp',])
   viewerEnv.Install(pj(inst_paths['app_base'], 'Viewer'), infi_app_prog)

   # Only install *.jdef files on first pass.
   if 0 == variant_pass:
      jdef_files = ['iov_app.jdef',]
      jconf_files = ['viewer-nav.jconf', 'viewer-vp.jconf']

      viewerEnv.Install(pj(inst_paths['app_base'], 'Viewer'), jconf_files)
      viewerEnv.Install(pj(inst_paths['app_base'], 'Viewer'), jdef_files)
else:
   print "WARNING: Cannot build infi_app without Boost.program_options"

